#!/usr/bin/env bash

cat <<'EOF'
bar {
	position top
    workspace_buttons yes
    status_command python3 ~/.i3/i3status.py

    colors {
        background  #222222
        statusline  #dddddd
        separator   #666666
        focused_workspace   #0088CC #0088CC #ffffff
        active_workspace    #333333 #333333 #888888
        inactive_workspace  #333333 #333333 #888888
        urgent_workspace    #2f343a #900000 #ffffff
    }
}
EOF
