#!/usr/bin/env bash

[[ "${HOSTNAME}" = "zentux" ]] && echo 'set $PIXEL pixel 1'
[[ "${HOSTNAME}" = "LQ-D-0034" ]] && echo 'set $PIXEL pixel 2'

cat <<'EOF'
set $TERM terminator --geometry=600x400
set $RUN exec --no-startup-id

focus_follows_mouse no
floating_modifier Mod4

client.focused          #0088CC #0088CC #ffffff #dddddd
client.focused_inactive #333333 #333333 #888888 #292d2e
client.unfocused        #333333 #333333 #888888 #292d2e
client.urgent           #2f343a #900000 #ffffff #900000

font pango: DejaVu Sans Mono:style=Book 9

new_window  $PIXEL
new_float   $PIXEL
hide_edge_borders smart
EOF
