#!/usr/bin/env bash

cat <<'EOF'
mode "resize" {
    bindsym h resize shrink     width  10 px or 10 ppt
    bindsym j resize shrink     height 10 px or 10 ppt
    bindsym k resize grow       height 10 px or 10 ppt
    bindsym l resize grow       width  10 px or 10 ppt

    bindsym Left  resize shrink     width  10 px or 10 ppt
    bindsym Down  resize shrink     height 10 px or 10 ppt
    bindsym Up    resize grow       height 10 px or 10 ppt
    bindsym Right resize grow       width  10 px or 10 ppt

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
EOF
