#!/usr/bin/env bash

cat <<'EOF'
$RUN i3-monitor.sh -c
$RUN /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
$RUN insync start &
$RUN compton -b --config ~/.compton.conf
$RUN redshift-gtk -l 55.586:13.054 &
$RUN syndaemon -dtK &
$RUN parcellite --daemon &
$RUN eval $(ssh-agent)
EOF
