#!/usr/bin/env bash

cat <<'EOF'
for_window [window_role="VPN"] move workspace VPN
no_focus [window_role="VPN"]
EOF

for window in telegram-desktop chromium Remmina GitKraken; do
    echo -e "for_window [class=\"${window}\"] border pixel 0"
done
